# Processing Filters Configuration
# This file defines which ENI types and subtypes should be processed

# Filter configuration metadata
filter_info:
  name: "default_processing_filter"
  description: "Default processing filter for member insights"
  created: "2025-01-04"
  version: "1.0"

# Processing inclusion rules
# Each ENI type can specify:
# - List of specific subtypes: Process NULL subtypes PLUS the listed subtypes
# - "none" or empty: Process ONLY NULL subtypes (no explicit subtypes defined)
# 
# NOTE: NULL subtypes (eni_source_subtype IS NULL) are ALWAYS processed first for every ENI type.
# If you want to exclude an ENI type entirely, comment it out or remove it from the rules.

eni_processing_rules:
  # Process affiliations data (NULL subtypes only - no explicit subtypes defined)
  airtable_affiliations:
  
  # Process deals sourced data (NULL subtypes only - no explicit subtypes defined)
  airtable_deals_sourced:
  
  # Process airtable notes (NULL subtypes + specific subtypes listed below)
  airtable_notes:
    - investing_preferences
    - intro_preferences
  
  # Process recurroo data (NULL subtypes + specific subtypes listed below)
  recurroo:
    - biography
    - asset_class
    - sector
    - social
  
  # Process WhatsApp messages (NULL subtypes + specific subtypes listed below)
  # whatsapp_messages:
  #   - "venture"
  #   - "needs_leads"
  
  # Process member requests (NULL subtypes + specific subtypes listed below)
  member_requests:
    - "requested"
  
  # Explicitly excluded (commented out for clarity)
  # pipedrive_notes: "none"  # Skip entirely

# Global processing settings
processing_settings:
  # Whether to log skipped records
  log_skipped_records: true
  
  # Whether to show processing statistics
  show_processing_stats: true
  
  # Whether to validate all configured subtypes exist
  validate_subtypes: true 